[package]
name = "cnctd_solana"
version = "0.1.0"
edition = "2021"
authors = ["Connected Dot Inc.", "Kyle Ebner <kyle@cnctd.world>"]
description = "tools for interacting between the cnctd ecosystem and the solana blockchain."
repository = "https://github.com/Connected-Dot/cnctd_solana"
license = "MIT"
keywords = ["module"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
borsh = "1.5.5"
mpl-token-metadata = "5.1.0"
serde = { version = "1.0.217", features = ["derive"] }
solana-program = "2.2.1"
